{
  ruby      => { name => 'Ruby', keywords => ['Ruby', 'ruby', 'Rails', 'Sinatra'] },
  python    => { name => 'Python', keywords => ['Python', 'python', 'Django', 'NumPy', 'SciPy'] },
  perl      => { name => 'Perl', keywords => ['Perl', 'perl', 'Mojolicious', 'Amon2', 'Catalyst'] },
  scala     => { name => 'Scala', keywords => ['Scala', 'scala'] },
  php       => { name => 'PHP', keywords => ['PHP', 'php', 'CakePHP'] },
  objc      => { name => 'Objective-C', keywords => ['Objective-C', 'objective-c', 'ObjC', 'objc'] },
  js        => { name => 'JavaScript', keywords => ['JavaScript', 'javascript', 'Node', 'AngularJS', 'Angular.js', 'Backbone.js'] },
  haskell   => { name => 'Haskell', keywords => ['Haskell', 'haskell'] },
  java      => { name => 'Java', keywords => ['Java', 'java'] },
  cs        => { name => 'C#', keywords => ['C#'] },
  lisp      => { name => 'LISP', keywords => ['LISP', 'Lisp', 'lisp'] },
  go        => { name => 'Go', keywords => ['Golang', 'golang', 'Go言語', 'go言語'] },
  cpp       => { name => 'C/C++', keywords => ['C++', 'c++', 'C言語', 'c言語'] },
  basic     => { name => 'BASIC', keywords => ['BASIC', 'basic', 'VisualBasic', 'visualbasic'] },
  matlab    => { name => 'MATLAB', keywords => ['MATLAB', 'matlab'] },
  shell     => { name => 'Shell', keywords => ['bash', 'zsh', 'csh', 'tcsh', 'fish'] },
  html      => { name => 'HTML', keywords => ['HTML', 'html'] },
  html5     => { name => 'HTML5', keywords => ['HTML5', 'html5'] },
  css       => { name => 'CSS', keywords => ['CSS', 'css'] },

  cocos2d   => { name => 'cocos2d', keywords => ['cocos2d', 'cocos2D', 'cocos2d-x', 'cocos2dx'] },
  unity     => { name => 'Unity', keywords => ['Unity', 'unity'] },
  jquery    => { name => 'jQuery', keywords => ['jQuery', 'jquery'] },
  wordpress => { name => 'WordPress', keywords => ['WordPress', 'Wordpress', 'wordpress'] },

  mysql     => { name => 'MySQL', keywords => ['MySQL', 'mysql'] },
  mongodb   => { name => 'MongoDB', keywords => ['MongoDB', 'mongodb'] },
  redis     => { name => 'Redis', keywords => ['Redis', 'redis'] },
  db        => { name => 'DataBase', keywords => ['DataBase', 'Database', 'db', 'DB', 'データベース'] },

  apache    => { name => 'Apache', keywords => ['Apache', 'apache'] },
  nginx     => { name => 'Nginx', keywords => ['Nginx', 'nginx'] },
  chef      => { name => 'Chef', keywords => ['Chef', 'chef'] },
  vagrant   => { name => 'Vagrant', keywords => ['Vagrant', 'vagrant'] },
  docker    => { name => 'Docker', keywords => ['Docker', 'docker'] },
  ansible   => { name => 'Ansible', keywords => ['Ansible', 'ansible'] },

  ios       => { name => 'iOS', keywords => ['iOS', 'ios', 'iPhone', 'iphone'] },
  android   => { name => 'Android', keywords => ['Android', 'android'] },
  linux     => { name => 'Linux', keywords => ['Linux', 'linux'] },
  windows   => { name => 'Windows', keywords => ['Windows', 'windows'] },
  azure     => { name => 'Azure', keywords => ['Azure', 'azure'] },
  aws       => { name => 'AWS', keywords => ['AWS', 'aws', 'Amazon'] },
  cloud     => { name => 'Cloud', keywords => ['Cloud', 'cloud', 'クラウド'] },
  sns       => { name => 'SNS', keywords => ['SNS', 'sns', 'Facebook', 'facebook', 'Twitter', 'twitter', 'mixi'] },

  hackathon => { name => 'Hackathon', keywords => ['Hackathon', 'hackathon', 'ハッカソン'] },
  tdd       => { name => 'TDD/BDD', keywords => ['TDD', 'tdd', 'BDD', 'bdd', 'テスト駆動開発'] },
}
